package nri

import (
	"path/filepath"
	"strings"

	api "github.com/containerd/nri/pkg/api"
)

// ContainerNonoPath is the fixed path inside the container where the nono
// binary is accessible after the /nono directory is mounted.
const ContainerNonoPath = "/nono/nono"

// containerNonoDirPath is the directory mounted into the container.
// Mounting the directory (not the file) ensures the destination path is
// created by the OCI runtime even when it doesn't pre-exist in the rootfs.
//
// Invariant: no container image used with nono-nri should define its own
// /nono directory for a different purpose. If a container image already has
// /nono, this mount will silently shadow it. This is an accepted constraint
// of the current design.
const containerNonoDirPath = "/nono"

// defaultContainerPATH is used when the container spec carries no PATH entry.
// Matches the default set by most Linux distribution base images.
const defaultContainerPATH = "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

// BuildAdjustment constructs a ContainerAdjustment that wraps the container
// process with nono and extends exec coverage via wrapper scripts.
//
// For every sandboxed container it:
//   - Prepends [/nono/nono, wrap, --profile, <profile>, --] to process.args
//     so PID 1 is sandboxed before it starts.
//   - Bind-mounts the host directory containing the nono binary into the
//     container at /nono (virtiofs for Kata, plain bind for runc).
//     The same directory holds wrapper scripts for common interpreters
//     (sh, bash, python3, …) generated by the DaemonSet init container.
//   - Injects NONO_PROFILE=<profile> so wrapper scripts pick up the correct
//     profile without a separate config lookup.
//   - Prepends /nono to the container's PATH so name-only execs
//     (e.g. kubectl exec pod -- bash) resolve to the wrapper first.
//     exec'd processes inherit the container's process env, so this PATH
//     modification applies to all subsequent execs inside the container.
//   - Applies seccomp (if non-nil) via SetLinuxSeccompPolicy. For Kata, the
//     kata-agent enforces this policy inside the VM when disable_guest_seccomp
//     is false in the QEMU config.
//
// vmRootfs is reserved for future use and has no effect on the adjustment.
//
// It is safe to call with a container that has nil or empty args.
func BuildAdjustment(ctr *api.Container, profile, hostBinPath string, vmRootfs bool, seccomp *api.LinuxSeccomp) *api.ContainerAdjustment {
	prefix := []string{ContainerNonoPath, "wrap", "--profile", profile, "--"}
	orig := ctr.GetArgs()
	newArgs := make([]string, 0, len(prefix)+len(orig))
	newArgs = append(newArgs, prefix...)
	newArgs = append(newArgs, orig...)

	adj := &api.ContainerAdjustment{}
	adj.SetArgs(newArgs)

	adj.AddMount(&api.Mount{
		Source:      filepath.Dir(hostBinPath),
		Destination: containerNonoDirPath,
		Type:        "bind",
		Options:     []string{"bind", "ro", "rprivate"},
	})

	// NONO_PROFILE lets wrapper scripts apply the right profile for execs
	// that are intercepted after PID 1 (kubectl exec, child processes).
	// RemoveEnv strips any value the container spec may have pre-set so our
	// value is authoritative regardless of NRI env-merge ordering.
	adj.RemoveEnv("NONO_PROFILE")
	adj.AddEnv("NONO_PROFILE", profile)

	// Prepend /nono to PATH so wrapper scripts shadow real interpreter binaries.
	// We read the container's existing PATH from its OCI process env and
	// prepend /nono; if no PATH is set we fall back to the distribution default.
	// RemoveEnv ensures no duplicate PATH survives that could shadow our value.
	// OCI env entries must be in KEY=VALUE form per the runtime spec; malformed
	// entries without '=' are not matched and are left for the runtime to handle.
	existingPATH := defaultContainerPATH
	for _, entry := range ctr.GetEnv() {
		if strings.HasPrefix(entry, "PATH=") {
			existingPATH = strings.TrimPrefix(entry, "PATH=")
			break
		}
	}
	adj.RemoveEnv("PATH")
	adj.AddEnv("PATH", containerNonoDirPath+":"+existingPATH)

	if seccomp != nil {
		adj.SetLinuxSeccompPolicy(seccomp)
	}

	return adj
}
