package nri

import api "github.com/containerd/nri/pkg/api"

// Seccomp profile names accepted by seccomp_profile in the TOML config.
const (
	SeccompProfileRuntimeDefault = "runtime-default"
	SeccompProfileRestricted     = "restricted"
)

// BuildSeccompPolicy returns a LinuxSeccomp policy for the named profile,
// or nil when profile is empty (seccomp injection disabled).
// The returned policy is ready to pass to ContainerAdjustment.SetLinuxSeccompPolicy.
func BuildSeccompPolicy(profile string) *api.LinuxSeccomp {
	switch profile {
	case SeccompProfileRuntimeDefault:
		return &api.LinuxSeccomp{
			DefaultAction: "SCMP_ACT_ERRNO",
			Architectures: []string{"SCMP_ARCH_X86_64"},
			Syscalls:      []*api.LinuxSyscall{{Names: runtimeDefaultAllowed, Action: "SCMP_ACT_ALLOW"}},
		}
	case SeccompProfileRestricted:
		return &api.LinuxSeccomp{
			DefaultAction: "SCMP_ACT_ERRNO",
			Architectures: []string{"SCMP_ARCH_X86_64"},
			Syscalls:      []*api.LinuxSyscall{{Names: restrictedAllowed(), Action: "SCMP_ACT_ALLOW"}},
		}
	default:
		return nil
	}
}

// restrictedAllowed returns runtimeDefaultAllowed minus restrictedBlocked.
// Called once per container creation when seccomp_profile = "restricted".
func restrictedAllowed() []string {
	skip := make(map[string]bool, len(restrictedBlocked))
	for _, s := range restrictedBlocked {
		skip[s] = true
	}
	out := make([]string, 0, len(runtimeDefaultAllowed))
	for _, s := range runtimeDefaultAllowed {
		if !skip[s] {
			out = append(out, s)
		}
	}
	return out
}

// restrictedBlocked is the delta between "runtime-default" and "restricted":
// syscalls that RuntimeDefault allows but we additionally deny for untrusted
// AI-agent workloads. Each entry is a deliberate security decision.
var restrictedBlocked = []string{
	// Prevent the workload from weakening or removing its own seccomp filter.
	// A root process inside the VM could otherwise call seccomp(2) to install
	// a permissive replacement filter, negating this policy.
	"seccomp",
	// Cross-process memory read/write. CAP_SYS_PTRACE is required on modern
	// kernels, but we block the syscall as belt-and-suspenders for AI workloads.
	"ptrace",
	// io_uring has been an active container escape vector:
	// CVE-2022-2639, CVE-2023-2598. Use "runtime-default" if a workload
	// explicitly requires high-performance async I/O.
	"io_uring_setup",
	"io_uring_enter",
	"io_uring_register",
	// Steal open file descriptors from another process in the same namespace.
	"pidfd_getfd",
}

// runtimeDefaultAllowed is the Docker/moby RuntimeDefault seccomp allowlist.
// Source: github.com/moby/moby profiles/seccomp/default_linux.go
//
// Only SCMP_ARCH_X86_64 is declared. SCMP_ARCH_X86 (32-bit compat via
// int 0x80) and SCMP_ARCH_X32 (x32 ABI) are omitted: the kata guest kernel
// targets 64-bit workloads and we do not expect 32-bit binaries in AI agent
// containers. The _32-suffixed names from moby's list (chown32, getuid32, …)
// are also removed: they exist only in the i386 syscall table and are
// unreachable from 64-bit processes.
var runtimeDefaultAllowed = []string{
	"accept",
	"accept4",
	"access",
	"adjtimex",
	"alarm",
	"bind",
	"brk",
	"capget",
	"capset",
	"chdir",
	"chmod",
	"chown",
	"clock_adjtime",
	"clock_adjtime64",
	"clock_getres",
	"clock_getres_time64",
	"clock_gettime",
	"clock_gettime64",
	"clock_nanosleep",
	"clock_nanosleep_time64",
	// arch_prctl: x86-64 TLS setup (ARCH_SET_FS). Called by the glibc dynamic
	// linker before any user code runs; its absence causes immediate exit 127.
	"arch_prctl",
	"close",
	"close_range",
	// clone/clone3: thread creation (pthread_create). clone3 is preferred by
	// glibc 2.32+ on new kernels; both are needed for compatibility.
	"clone",
	"clone3",
	"connect",
	"copy_file_range",
	"creat",
	"dup",
	"dup2",
	"dup3",
	"epoll_create",
	"epoll_create1",
	"epoll_ctl",
	"epoll_ctl_old",
	"epoll_pwait",
	"epoll_pwait2",
	"epoll_wait",
	"epoll_wait_old",
	"eventfd",
	"eventfd2",
	"execve",
	"execveat",
	"exit",
	"exit_group",
	"faccessat",
	"faccessat2",
	"fadvise64",
	"fadvise64_64",
	"fallocate",
	"fanotify_mark",
	"fchdir",
	"fchmod",
	"fchmodat",
	"fchown",
	"fchownat",
	"fcntl",
	"fcntl64",
	"fdatasync",
	"fgetxattr",
	"flistxattr",
	"flock",
	"fork",
	"fremovexattr",
	"fsetxattr",
	"fstat",
	"fstat64",
	"fstatat64",
	"fstatfs",
	"fstatfs64",
	"fsync",
	"ftruncate",
	"ftruncate64",
	"futex",
	"futex_time64",
	"futex_waitv",
	"get_mempolicy",
	"get_robust_list",
	"get_thread_area",
	"getcpu",
	"getcwd",
	"getdents",
	"getdents64",
	"getegid",
	"geteuid",
	"getgid",
	"getgroups",
	"getitimer",
	"getpeername",
	"getpgid",
	"getpgrp",
	"getpid",
	"getppid",
	"getpriority",
	"getrandom",
	"getresgid",
	"getresuid",
	"getrlimit",
	"getrusage",
	"getsid",
	"getsockname",
	"getsockopt",
	"gettid",
	"gettimeofday",
	"getuid",
	"getxattr",
	"inotify_add_watch",
	"inotify_init",
	"inotify_init1",
	"inotify_rm_watch",
	"io_cancel",
	"io_destroy",
	"io_getevents",
	"io_pgetevents",
	"io_pgetevents_time64",
	"io_setup",
	"io_submit",
	"io_uring_enter",
	"io_uring_register",
	"io_uring_setup",
	"ioctl",
	"ioprio_get",
	"ioprio_set",
	"ipc",
	"kill",
	"landlock_add_rule",
	"landlock_create_ruleset",
	"landlock_restrict_self",
	"lchown",
	"lgetxattr",
	"link",
	"linkat",
	"listen",
	"listxattr",
	"llistxattr",
	"lremovexattr",
	"lseek",
	"lsetxattr",
	"lstat",
	"lstat64",
	"madvise",
	"mbind",
	// modify_ldt: x86 LDT segment management; present in moby RuntimeDefault.
	"modify_ldt",
	"membarrier",
	"memfd_create",
	"memfd_secret",
	"mincore",
	"mkdir",
	"mkdirat",
	"mknod",
	"mknodat",
	"mlock",
	"mlock2",
	"mlockall",
	"mmap",
	"mmap2",
	"mprotect",
	"mremap",
	"msgctl",
	"msgget",
	"msgrcv",
	"msgsnd",
	"msync",
	"munlock",
	"munlockall",
	"munmap",
	"nanosleep",
	"newfstatat",
	"nice",
	"oldfstat",
	"oldlstat",
	"oldolduname",
	"oldstat",
	"olduname",
	"open",
	"openat",
	"openat2",
	"pause",
	"pidfd_getfd",
	"pidfd_open",
	"pidfd_send_signal",
	"pipe",
	"pipe2",
	"poll",
	"ppoll",
	"ppoll_time64",
	"prctl",
	"pread64",
	"preadv",
	"preadv2",
	"prlimit64",
	"process_madvise",
	"pselect6",
	"pselect6_time64",
	"ptrace",
	"pwrite64",
	"pwritev",
	"pwritev2",
	"read",
	"readahead",
	"readlink",
	"readlinkat",
	"readv",
	"recv",
	"recvfrom",
	"recvmmsg",
	"recvmmsg_time64",
	"recvmsg",
	"remap_file_pages",
	"removexattr",
	"rename",
	"renameat",
	"renameat2",
	"restart_syscall",
	"rmdir",
	"rseq",
	"rt_sigaction",
	"rt_sigpending",
	"rt_sigprocmask",
	"rt_sigqueueinfo",
	"rt_sigreturn",
	"rt_sigsuspend",
	"rt_sigtimedwait",
	"rt_sigtimedwait_time64",
	"rt_tgsigqueueinfo",
	"sched_getaffinity",
	"sched_getattr",
	"sched_getparam",
	"sched_get_priority_max",
	"sched_get_priority_min",
	"sched_getscheduler",
	"sched_rr_get_interval",
	"sched_rr_get_interval_time64",
	"sched_setaffinity",
	"sched_setattr",
	"sched_setparam",
	"sched_setscheduler",
	"sched_yield",
	"seccomp",
	"select",
	"semctl",
	"semget",
	"semop",
	"semtimedop",
	"semtimedop_time64",
	"send",
	"sendfile",
	"sendfile64",
	"sendmmsg",
	"sendmsg",
	"sendto",
	"set_mempolicy",
	"set_robust_list",
	"set_thread_area",
	"set_tid_address",
	"setfsgid",
	"setfsuid",
	"setgid",
	"setgroups",
	"setitimer",
	"setpgid",
	"setpriority",
	"setregid",
	"setresgid",
	"setresuid",
	"setreuid",
	"setsid",
	"setsockopt",
	"setuid",
	"setxattr",
	"shmat",
	"shmctl",
	"shmdt",
	"shmget",
	"shutdown",
	"sigaltstack",
	"signal",
	"signalfd",
	"signalfd4",
	"sigprocmask",
	"sigreturn",
	"socket",
	"socketcall",
	"socketpair",
	"splice",
	"stat",
	"stat64",
	"statfs",
	"statfs64",
	"statx",
	"stime",
	"symlink",
	"symlinkat",
	"sync",
	"sync_file_range",
	"sync_file_range2",
	"syncfs",
	"sysinfo",
	"tee",
	"tgkill",
	"time",
	"timer_create",
	"timer_delete",
	"timer_getoverrun",
	"timer_gettime",
	"timer_gettime64",
	"timer_settime",
	"timer_settime64",
	"timerfd_create",
	"timerfd_gettime",
	"timerfd_gettime64",
	"timerfd_settime",
	"timerfd_settime64",
	"times",
	"tkill",
	"truncate",
	"truncate64",
	"ugetrlimit",
	"umask",
	"uname",
	"unlink",
	"unlinkat",
	"utime",
	"utimensat",
	"utimensat_time64",
	"utimes",
	"vfork",
	"vmsplice",
	"wait4",
	"waitid",
	"waitpid",
	"write",
	"writev",
}
